=== ErikRanea/E-LeagueMaker/lenguajeDeMarcas/Fase 3/ResultadoUltimaJornada/ResultadoUltimaJornada.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Elemento raÃ­z -->
  <xs:element name="resultado_jornada">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="competicion" type="competicionType" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Tipo complejo para 'competicion' -->
  <xs:complexType name="competicionType">
    <xs:sequence>
      <xs:element name="nombre_competicion" type="xs:string"/>
      <xs:element name="jornada" type="jornadaType" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:integer" use="required"/>
  </xs:complexType>

  <!-- Tipo complejo para 'jornada' -->
  <xs:complexType name="jornadaType">
    <xs:sequence>
      <xs:element name="numero_jornada" type="xs:integer"/>
      <xs:element name="Fecha_jornada" type="xs:date"/>
      <xs:element name="enfrentamiento" type="enfrentamientoType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:integer" use="required"/>
  </xs:complexType>

  <!-- Tipo complejo para 'enfrentamiento' -->
  <xs:complexType name="enfrentamientoType">
    <xs:sequence>
      <xs:element name="cod_equipo_local" type="xs:integer"/>
      <xs:element name="cod_equipo_visitante" type="xs:integer"/>
      <xs:element name="ganador" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:integer" use="required"/>
  </xs:complexType>

</xs:schema>

=== ErikRanea/E-LeagueMaker/lenguajeDeMarcas/Fase 3/ResultadoUltimaJornada/ResultadoUltimaJornada_con_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<resultado_jornada xmlns:xs = "http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation = "ResultadoUltimaJornada.xsd">
   <competicion id="1">
      <nombre_competicion>LOL_League</nombre_competicion>
      <jornada id="304">
         <numero_jornada>1</numero_jornada>
         <Fecha_jornada>2024-06-01</Fecha_jornada>
         <enfrentamiento id="685">
            <cod_equipo_local>4</cod_equipo_local>
            <cod_equipo_visitante>2</cod_equipo_visitante>
            <ganador>Visitante</ganador>
         </enfrentamiento>
         <enfrentamiento id="686">
            <cod_equipo_local>1</cod_equipo_local>
            <cod_equipo_visitante>3</cod_equipo_visitante>
            <ganador>Visitante</ganador>
         </enfrentamiento>
      </jornada>
   </competicion>
   <competicion id="2">
      <nombre_competicion>CS_go_League</nombre_competicion>
      <jornada id="307">
         <numero_jornada>1</numero_jornada>
         <Fecha_jornada>2024-06-01</Fecha_jornada>
         <enfrentamiento id="691">
            <cod_equipo_local>8</cod_equipo_local>
            <cod_equipo_visitante>5</cod_equipo_visitante>
            <ganador>Visitante</ganador>
         </enfrentamiento>
         <enfrentamiento id="692">
            <cod_equipo_local>6</cod_equipo_local>
            <cod_equipo_visitante>7</cod_equipo_visitante>
            <ganador>Visitante</ganador>
         </enfrentamiento>
      </jornada>
   </competicion>
   <competicion id="3">
      <nombre_competicion>Valorant_league</nombre_competicion>
      <jornada id="310">
         <numero_jornada>1</numero_jornada>
         <Fecha_jornada>2024-06-01</Fecha_jornada>
         <enfrentamiento id="697">
            <cod_equipo_local>12</cod_equipo_local>
            <cod_equipo_visitante>11</cod_equipo_visitante>
            <ganador>Visitante</ganador>
         </enfrentamiento>
         <enfrentamiento id="698">
            <cod_equipo_local>9</cod_equipo_local>
            <cod_equipo_visitante>10</cod_equipo_visitante>
            <ganador>Visitante</ganador>
         </enfrentamiento>
      </jornada>
   </competicion>
   <competicion id="4">
      <nombre_competicion>R6_league</nombre_competicion>
      <jornada id="313">
         <numero_jornada>1</numero_jornada>
         <Fecha_jornada>2024-06-01</Fecha_jornada>
         <enfrentamiento id="703">
            <cod_equipo_local>13</cod_equipo_local>
            <cod_equipo_visitante>14</cod_equipo_visitante>
            <ganador>Visitante</ganador>
         </enfrentamiento>
         <enfrentamiento id="704">
            <cod_equipo_local>15</cod_equipo_local>
            <cod_equipo_visitante>16</cod_equipo_visitante>
            <ganador>Visitante</ganador>
         </enfrentamiento>
      </jornada>
   </competicion>
</resultado_jornada>
