=== ErikRanea/E-LeagueMaker/lenguajeDeMarcas/Fase 3/ResultadoUltimaJornada/ResultadoUltimaJornada.dtd
<!ELEMENT resultado_jornada (jornada)>
<!ELEMENT jornada (numero_jornada, enfrentamiento+)>
<!ATTLIST jornada 
    id CDATA #REQUIRED
>
<!ELEMENT numero_jornada (#PCDATA)>
<!ELEMENT enfrentamiento (cod_equipo_local, cod_equipo_visitante, ganador)>
<!ATTLIST enfrentamiento 
    id CDATA #REQUIRED
>
<!ELEMENT cod_equipo_local (#PCDATA)>
<!ELEMENT cod_equipo_visitante (#PCDATA)>
<!ELEMENT ganador (#PCDATA)>

=== ErikRanea/E-LeagueMaker/lenguajeDeMarcas/Fase 3/ResultadoUltimaJornada/ResultadoUltimaJornada_con_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resultado_jornada SYSTEM "ResultadoUltimaJornada.dtd">

<resultado_jornada>
    <jornada id="13">
        <numero_jornada>1</numero_jornada>
        <enfrentamiento id="25">
            <cod_equipo_local>1</cod_equipo_local>
            <cod_equipo_visitante>4</cod_equipo_visitante>
            <ganador>Visitante</ganador>
        </enfrentamiento>
        <enfrentamiento id="26">
            <cod_equipo_local>2</cod_equipo_local>
            <cod_equipo_visitante>3</cod_equipo_visitante>
            <ganador>Visitante</ganador>
        </enfrentamiento>
    </jornada>
</resultado_jornada>
