=== ErikRanea/E-LeagueMaker/lenguajeDeMarcas/Fase 3/Clasificacion/Clasificacion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Elemento raÃ­z -->
  <xs:element name="clasificacion">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="competicion" type="competicionType" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Tipo complejo para 'competicion' -->
  <xs:complexType name="competicionType">
    <xs:sequence>
      <xs:element name="nombre_competicion" type="xs:string"/>
      <xs:element name="fecha_inicio_competicion" type="xs:date"/>
      <xs:element name="fecha_fin_competicion" type="xs:date"/>
      <xs:element name="nombre_juego" type="xs:string"/>
      <xs:element name="equipo" type="equipoType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:integer" use="required"/>
  </xs:complexType>

  <!-- Tipo complejo para 'equipo' -->
  <xs:complexType name="equipoType">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="puntos" type="xs:integer"/>
      <xs:element name="posicion" type="xs:integer"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:integer" use="required"/>
  </xs:complexType>

</xs:schema>

=== ErikRanea/E-LeagueMaker/lenguajeDeMarcas/Fase 3/Clasificacion/Clasificacion_con_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>

<clasificacion xmlns:xs = "http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation = "Clasificacion.xsd">
    <competicion id="1">
        <equipo id="1">
            <nombre>Equipo LoL 1</nombre>
            <puntos>0</puntos>
            <posicion>1</posicion>
        </equipo>
        <equipo id="4">
            <nombre>Equipo LoL 4</nombre>
            <puntos>0</puntos>
            <posicion>2</posicion>
        </equipo>
        <equipo id="3">
            <nombre>Equipo LoL 3</nombre>
            <puntos>0</puntos>
            <posicion>3</posicion>
        </equipo>
        <equipo id="2">
            <nombre>Equipo LoL 2</nombre>
            <puntos>0</puntos>
            <posicion>4</posicion>
        </equipo>
    </competicion>
</clasificacion>
